### ISSUE TITLE
Custom Domain in production deployment

### ISSUE THREAD

**Issue by peterpersiel** [sap-software/abap-saas-reference-solution#1]
Best practice for production deployment ist to use a custom domain.

Please check the example for prod.mtaext

https://github.com/sap-software/abap-saas-reference-solution/blob/a71c5b40e2b027b1878f341d1f5c97503a8f5b43/extensions/examples/prod.mtaext#L6
Instead of default-domain please provide example for custom domain: mydomain.com

https://github.com/sap-software/abap-saas-reference-solution/blob/a71c5b40e2b027b1878f341d1f5c97503a8f5b43/extensions/examples/prod.mtaext#L7

The route-prefix should be `""`, so that

`cis${route-prefix}.${app-domain}` becomes `cis.mydomain.com`

and

`*${route-prefix}.${app-domain}` becomes `*.mydomain.com`

Please add wildcard route in approuter module in the prod.mtaext example so that it is clear that routes do not have to be created per subscription:

```YAML
modules:
  - name: approuter
    parameters:
      routes:
        - route: "cis${route-prefix}.${app-domain}"
        - route: "*${route-prefix}.${app-domain}"
```
